export const ProvinceConstants = [
    "Daerah Istimewa Yogyakarta",
    "Jawa Tengah",
    "Jawa Timur",
    "Jawa Barat",
    "DKI Jakarta",
    "Banten",
    "Bali",
    "Lampung",
    "Riau",
    "Sumatera Selatan",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "Sulawesi Selatan",
    "Kalimantan Barat",
    "Kalimantan Timur",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Utara",
    "Nusa Tenggara Barat",
    "Papua",
  ]